"""Style schema and preset management."""

from visionstyle.style.presets import (
    PresetInfo,
    builtin_presets_dir,
    delete_preset,
    list_presets,
    load_preset,
    resolve_preset_path,
    save_preset,
    user_presets_dir,
)
from visionstyle.style.schema import (
    SCHEMA_VERSION,
    BoxStyle,
    EffectsStyle,
    FillStyle,
    GlassEffect,
    GlowEffect,
    GrainEffect,
    LabelStyle,
    LinePattern,
    PaletteSpec,
    ShadowEffect,
    StrokeStyle,
    Style,
    TrailStyle,
    VignetteEffect,
)

__all__ = [
    "SCHEMA_VERSION",
    "BoxStyle",
    "EffectsStyle",
    "FillStyle",
    "GlassEffect",
    "GlowEffect",
    "GrainEffect",
    "LabelStyle",
    "LinePattern",
    "PaletteSpec",
    "PresetInfo",
    "ShadowEffect",
    "StrokeStyle",
    "Style",
    "TrailStyle",
    "VignetteEffect",
    "builtin_presets_dir",
    "delete_preset",
    "list_presets",
    "load_preset",
    "resolve_preset_path",
    "save_preset",
    "user_presets_dir",
]
